# Generated by Django 2.1.3 on 2018-12-20 19:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("pro", "0010_auto_20181220_1857"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubdomainDataFeed",
            new_name="UrlDataFeed",
        ),
    ]
