# Generated by Django 2.1.7 on 2019-02-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="organizationreport",
            table=None,
        ),
        migrations.AlterModelTable(
            name="urlreport",
            table=None,
        ),
        migrations.AlterModelTable(
            name="vulnerabilitystatistic",
            table=None,
        ),
    ]
