# Generated by Django 2.1.7 on 2019-02-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_auto_20190222_1047"),
    ]

    database_operations = [migrations.AlterModelTable("VulnerabilityStatistic", "map_vulnerabilitystatistic")]

    state_operations = [migrations.DeleteModel("VulnerabilityStatistic")]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=database_operations, state_operations=state_operations)
    ]
