# Generated by Django 2.1.7 on 2019-04-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20190308_1317'),
    ]

    database_operations = [migrations.AlterModelTable('OrganizationReport', 'map_organizationreport')]

    state_operations = [migrations.DeleteModel('OrganizationReport')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
