# Generated by Django 3.1.6 on 2021-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0009_auto_20200530_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlreport",
            name="is_the_newest",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="The newest url report allows for quick retrieval of the current state, it prevents complex queries.",
            ),
        ),
    ]
