# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_auto_20170316_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('when', models.DateTimeField()),
                ('calculation', models.TextField()),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UrlRating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('when', models.DateTimeField()),
                ('calculation', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.Url')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
