# Generated by Django 2.0.7 on 2018-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0017_auto_20180420_0913"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationrating",
            name="high_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) high risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="high_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls with (1 or more) high risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="low_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) low risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="low_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls with (1 or more) low risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="medium_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) medium risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="medium_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls with (1 or more) medium risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="total_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints for this url."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="total_issues",
            field=models.IntegerField(default=0, help_text="The summed number of all vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="total_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls for this organization."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="high_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) high risk issues."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="low_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) low risk issues."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="medium_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) medium risk issues."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="total_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints for this url."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="total_issues",
            field=models.IntegerField(default=0, help_text="The summed number of all vulnerabilities and failures."),
        ),
    ]
