# Generated by Django 2.0.7 on 2018-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0021_auto_20180917_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationrating",
            name="explained_endpoint_issues_high",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_endpoint_issues_low",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_endpoint_issues_medium",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_high",
            field=models.IntegerField(default=0, help_text="The number of high risk vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_high_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) high risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_high_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls with (1 or more) high risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_low",
            field=models.IntegerField(default=0, help_text="The number of low risk vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_low_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) low risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_low_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls with (1 or more) low risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_medium",
            field=models.IntegerField(default=0, help_text="The number of medium risk vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_medium_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) medium risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_medium_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls with (1 or more) medium risk issues."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_total_endpoint_issues",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_total_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints for this url."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_total_issues",
            field=models.IntegerField(default=0, help_text="The summed number of all vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_total_url_issues",
            field=models.IntegerField(default=0, help_text="Total amount of issues on url level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_total_urls",
            field=models.IntegerField(default=0, help_text="Amount of urls for this organization."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_url_issues_high",
            field=models.IntegerField(default=0, help_text="Number of high issues on url level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_url_issues_low",
            field=models.IntegerField(default=0, help_text="Number of low issues on url level."),
        ),
        migrations.AddField(
            model_name="organizationrating",
            name="explained_url_issues_medium",
            field=models.IntegerField(default=0, help_text="Number of medium issues on url level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_endpoint_issues_high",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_endpoint_issues_low",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_endpoint_issues_medium",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_high",
            field=models.IntegerField(default=0, help_text="The number of high risk vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_high_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) high risk issues."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_low",
            field=models.IntegerField(default=0, help_text="The number of low risk vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_low_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) low risk issues."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_medium",
            field=models.IntegerField(default=0, help_text="The number of medium risk vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_medium_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints with (1 or more) medium risk issues."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_total_endpoint_issues",
            field=models.IntegerField(default=0, help_text="Total amount of issues on endpoint level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_total_endpoints",
            field=models.IntegerField(default=0, help_text="Amount of endpoints for this url."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_total_issues",
            field=models.IntegerField(default=0, help_text="The summed number of all vulnerabilities and failures."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_total_url_issues",
            field=models.IntegerField(default=0, help_text="Total amount of issues on url level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_url_issues_high",
            field=models.IntegerField(default=0, help_text="Number of high issues on url level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_url_issues_low",
            field=models.IntegerField(default=0, help_text="Number of low issues on url level."),
        ),
        migrations.AddField(
            model_name="urlrating",
            name="explained_url_issues_medium",
            field=models.IntegerField(default=0, help_text="Number of medium issues on url level."),
        ),
    ]
