# Generated by Django 2.0.8 on 2018-10-25 09:16

import django.db.models.deletion
import django_countries.fields
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0038_auto_20180824_0959"),
        ("map", "0024_vulnerabilitystatistic_scan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="map_data_cache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        db_index=True, help_text="Part of the combination shown on the map.", max_length=2
                    ),
                ),
                ("when", models.DateField()),
                (
                    "filters",
                    models.CharField(
                        blank=True, db_index=True, help_text="Any set of desired scan_types", max_length=255, null=True
                    ),
                ),
                ("dataset", jsonfield.fields.JSONField()),
                (
                    "organization_type",
                    models.ForeignKey(
                        help_text="Part of the combination shown on the map.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.OrganizationType",
                    ),
                ),
            ],
        ),
    ]
