# Generated by Django 2.0.8 on 2018-10-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0038_auto_20180824_0959'),
        ('map', '0026_auto_20181025_0916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='map_data_cache',
            new_name='MapDataCache',
        ),
    ]
