# Generated by Django 2.0.8 on 2018-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0028_mapdatacache_cached_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerabilitystatistic",
            name="endpoints",
            field=models.PositiveIntegerField(
                default=0, help_text="Makes only sense on the total number of vulnerabilities"
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilitystatistic",
            name="urls",
            field=models.PositiveIntegerField(
                default=0, help_text="Makes only sense on the total number of vulnerabilities"
            ),
        ),
    ]
