# Generated by Django 2.1.3 on 2018-12-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0030_configuration_is_reported"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationrating",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="urlrating",
            name="rating",
        ),
    ]
