# Generated by Django 2.1.3 on 2018-12-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0031_auto_20181213_1116"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationrating",
            options={
                "get_latest_by": "when",
                "verbose_name": "Organization Rating",
                "verbose_name_plural": "Organization Ratings",
            },
        ),
    ]
