# Generated by Django 2.1.5 on 2019-01-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0034_auto_20190123_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="organization_type",
            field=models.ForeignKey(
                help_text="Part of the combination shown on the map.",
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.OrganizationType",
                verbose_name="Layer",
            ),
        ),
    ]
