# Generated by Django 2.1.5 on 2019-01-24 20:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0035_auto_20190124_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeregion",
            name="import_start_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
