# Generated by Django 2.1.5 on 2019-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0036_administrativeregion_import_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeregion",
            name="import_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
