# Generated by Django 2.1.7 on 2019-02-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_auto_20190222_1001'),
    ]

    database_operations = [
        migrations.AlterModelTable('OrganizationReport', 'map_organizationreport'),
        migrations.AlterModelTable('UrlReport', 'map_urlreport'),
        migrations.AlterModelTable('VulnerabilityStatistic', 'map_vulnerabilitystatistic'),
    ]

    state_operations = [
        migrations.DeleteModel('OrganizationReport'),
        migrations.DeleteModel('UrlReport'),
        migrations.DeleteModel('VulnerabilityStatistic'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=database_operations, state_operations=state_operations)
    ]
