# Generated by Django 2.1.7 on 2019-03-15 12:06

import django.db.models.deletion
import django_countries.fields
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0053_url_do_not_find_subdomains"),
        ("map", "0045_vulnerabilitystatistic_ok"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighLevelStatistic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        db_index=True, help_text="Part of the combination shown on the map.", max_length=2
                    ),
                ),
                ("when", models.DateField()),
                ("report", jsonfield.fields.JSONField()),
                (
                    "organization_type",
                    models.ForeignKey(
                        help_text="Part of the combination shown on the map.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.OrganizationType",
                    ),
                ),
            ],
        ),
    ]
