# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_auto_20170922_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.Organization"),
        ),
    ]
