# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_url_organizations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="organization",
            new_name="organization_old",
        ),
        migrations.AlterUniqueTogether(
            name="url",
            unique_together=set([("organization_old", "url")]),
        ),
    ]
