# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_auto_20170927_1325"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="organizations",
            new_name="organization",
        ),
    ]
