# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 13:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20171113_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='organization_old',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='organizations.Organization'),
        ),
    ]
