# Generated by Django 2.0.4 on 2018-04-10 09:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_auto_20180403_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
    ]
