# Generated by Django 2.0.4 on 2018-04-10 09:57

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20180410_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='created_on',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(
                2016, 1, 1, 0, 0, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='is_dead_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_on',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(
                2016, 1, 1, 0, 0, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_dead_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
