# Generated by Django 2.0.4 on 2018-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0032_auto_20180410_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='organization type'),
        ),
    ]
