# Generated by Django 2.0.7 on 2018-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0035_auto_20180718_1814"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="onboarding_stage_set_on",
            field=models.DateTimeField(
                blank=True, help_text="When the onboarding stage was hit. Helps with time-outs.", null=True
            ),
        ),
    ]
