# Generated by Django 2.0.7 on 2018-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_auto_20180823_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='computed_subdomain',
            field=models.CharField(
                blank=True, db_index=True, help_text='Automatically computed by tldextract on save. Data entered manually will be overwritten.', max_length=255, null=True),
        ),
    ]
