# Generated by Django 2.1.3 on 2018-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0040_url_dns_supports_mx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
