# Generated by Django 2.1.3 on 2018-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0045_auto_20181213_0808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="kwargs",
            field=models.TextField(
                blank=True,
                default="{}",
                help_text="A JSON / dictionary with extra options for the parser to handle the dataset. This is different per parser. This field is highly coupled with the code of the parser.",
                max_length=5000,
                null=True,
            ),
        ),
    ]
