# Generated by Django 2.1.3 on 2018-12-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0046_auto_20181213_0854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='url',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='url',
            name='organization_old',
        ),
    ]
