# Generated by Django 2.1.5 on 2019-01-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0049_auto_20190128_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="file_source",
            field=models.FileField(
                blank=True,
                help_text="Fill out either the URL or File source. - A file upload has to be in a specific Excel format. You can download this format here: <a href='/static/empty_organizations_import_file.xlsx'>empty file</a>. You can also download an example that shows how to enter the data correctly. You can download the example here: <a href='/static/example_organizations_import_file.xlsx'>example file</a>",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="url_source",
            field=models.URLField(
                blank=True,
                help_text="Fill out either the URL or File source. - A url source hosts the data you wish to process, this can be an excel file. You can also upload the excel file below. This works great with online data sources that are published regularly. Make sure the parser exists as you cannot process any arbritrary download.",
                null=True,
            ),
        ),
    ]
