# Generated by Django 2.2.1 on 2019-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0055_organization_computed_name_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinate",
            name="calculated_area_hash",
            field=models.CharField(
                blank=True,
                help_text="Automatically calculated hash of the area field using the MD5 algorithm. This is used to try and optimize grouping on area (which is a very long text field, which is slow). The  hope is that this field will increase the speed of which grouping happens. If it doesn't,  we could calculate an even simpler hash by using the date + organization name. Note that if only one field is used for an organization (multipolygon, etc) this field is not required... We still developed it because we forgot what we made...",
                max_length=32,
                null=True,
            ),
        ),
    ]
