# Generated by Django 2.2.10 on 2020-03-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0057_auto_20200227_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='surrogate_id',
            field=models.CharField(
                blank=True, help_text='Any ID used to identify this organization in an external system. Used in automated imports via the API. Otherwise leave this field empty.', max_length=255, null=True),
        ),
    ]
