# Generated by Django 2.2.10 on 2020-08-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_organization_surrogate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promise',
        ),
    ]
