# Generated by Django 2.0.8 on 2018-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypersh', '0007_auto_20180405_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='communication_certificate',
            field=models.TextField(blank=True, help_text="A Base64 representation of a valid failmap .p12 certificate. You can create these yourself and use these certificates to enter the admin interface. This certificate encrypts traffic between failmap and it's workers. Do not share this certificate with anyone else, as they might get access to the admin interface. (this feature will be better / more easily implemented someday hopefully).", max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='region',
            field=models.CharField(
                help_text='Currently choose between: eu-central-1 and us-west-1. See https://docs.hyper.sh/hyper/Introduction/region.html', max_length=64),
        ),
    ]
