# Generated by Django 2.2.9 on 2020-02-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sidnupload",
            old_name="status",
            new_name="state",
        ),
    ]
