# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojsontype', models.CharField(blank=True, db_column='geoJsonType', max_length=20, null=True)),
                ('area', models.CharField(max_length=10000)),
            ],
            options={
                'managed': True,
                'db_table': 'coordinate',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('isdead', models.BooleanField(db_column='isDead', default=False)),
                ('isdeadsince', models.DateTimeField(blank=True, db_column='isDeadSince', null=True)),
                ('isdeadreason', models.CharField(blank=True, db_column='isDeadReason', max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization')),
            ],
            options={
                'db_table': 'url',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organizations.OrganizationType'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together=set([('organization', 'url')]),
        ),
    ]
