# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Used in the top lists to let visitors tweet to theorganization to wake them up.', max_length=150, null=True),
        ),
    ]
