# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20170913_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='uses_dns_wildcard',
            field=models.BooleanField(default=False, help_text='When true, this domain uses a DNS wildcard and any subdomain will resolve to something on this host.'),
        ),
    ]
