# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:12
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_url_uses_dns_wildcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='area',
            field=jsonfield.fields.JSONField(default=dict, help_text='GeoJson using the WGS84 (EPSG 4326) projection. Use simplified geometries to reduce the amount of data to transfer.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(help_text='Lowercase url name. For example: mydomain.tld or subdomain.domain.tld', max_length=150),
        ),
    ]
