# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20171127_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrating',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AlterIndexTogether(
            name='organizationrating',
            index_together=set([('when', 'id')]),
        ),
    ]
