# Generated by Django 2.1.3 on 2018-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_auto_20181029_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Whether this combination is shown on the map.'),
        ),
    ]
