# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypersh', '0001_hypersh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='last_result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credential',
            name='region',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='ContainerEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hypersh.ContainerConfiguration')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hypersh.ContainerGroup')),
            ],
        ),
        migrations.AddField(
            model_name='containergroup',
            name='environment_overlay',
            field=models.ManyToManyField(to='hypersh.ContainerEnvironment'),
        ),
        migrations.AddField(
            model_name='containerconfiguration',
            name='environment',
            field=models.ManyToManyField(to='hypersh.ContainerEnvironment'),
        ),
    ]
