# Generated by Django 2.0.4 on 2018-04-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypersh', '0004_errors_handling'),
        ('hypersh', '0004_auto_20180403_1547'),
    ]

    operations = [
    ]
