# Generated by Django 2.0.8 on 2018-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypersh', '0008_auto_20180925_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='communication_certificate',
            field=models.TextField(blank=True, help_text="A Base64 representation of a valid failmap .p12 certificate. You can create these yourself and use these certificates to enter the admin interface. This certificate encrypts traffic between failmap and it's workers. Do not share this certificate with anyone else, as they might get access to the admin interface. (this feature will be better / more easily implemented someday hopefully). You can create this value by running base64 filename. Do not use an online base64 service as that will leak your certificate :).", max_length=8000, null=True),
        ),
    ]
