# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_job_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="result_id",
            field=models.CharField(help_text="celery asyncresult ID for tracing task", max_length=255, unique=True),
        ),
    ]
