# Generated by Django 2.0.3 on 2018-03-21 09:39

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20171109_2243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="result",
            field=jsonfield.fields.JSONField(help_text="output of the task as JSON"),
        ),
    ]
