from django.core.management.base import BaseCommand

from failmap.map.rating import DetermineRatings
from failmap.scanners.scanner_tls_qualys import ScannerTlsQualys


class Command(BaseCommand):
    help = 'Perform scans, start somewhere and just go!'

    # https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/
    # def add_arguments(self, parser):
    #    parser.add_argument('poll_id', nargs='+', type=int)

    def handle(self, *args, **options):
        self.scan()

    def scan(self):

        extra_urls = """
        webmail.h-i-ambacht.nl
        afspraak.dantumadiel.eu
        schiedam.dataplatform.nl
        utrecht.dataplatform.nl
        mail.krimpenerwaard.nl
        defryskemarren.nl
        www.defryskemarren.nl
        hollandskroon.nl
        krimpenerwaard.nl
        www.krimpenerwaard.nl
        nissewaard.nl
        planonselfservice.nissewaard.nl
        redactie.nissewaard.nl
        ro-onlineprod.nissewaard.nl
        www.gemeentemaastricht.nl
        historischgis.delft.nl
        raad.delft.nl
        ris.delft.nl
        tedoen.delft.nl
        webcams.delft.nl
        ro.h-i-ambacht.nl
        simsite.defryskemarren.nl
        secure.hollandskroon.nl
        wijkteam.hollandskroon.nl
        beveiligd.defryskemarren.nl
        intranet.defryskemarren.nl
        secure.krimpenerwaard.nl
        simsite.krimpenerwaard.nl
        access.delft.nl
        www.amersfoort-kcc.nl
        digid.menameradiel.nl
        menameradiel.nl
        plannen.menameradiel.nl
        afspraken.hollandskroon.nl
        alkmaar.interaccess.nl
        dloket.belcombinatie.nl
        archief.gooisemeren.nl
        ftp.gooisemeren.nl
        raad.gooisemeren.nl
        ruimtelijkeplannen.gooisemeren.nl
        www.gooisemeren.nl
        cloud.hollandskroon.nl
        delft.nl
        media.delft.nl
        mail.menameradiel.nl
        mail2.menameradiel.nl
        webmail.menameradiel.nl
        www.nissewaard.nl
        woudenberg.nl
        www.woudenberg.nl
        formulieren.nissewaard.nl
        www.e-inwoner.nl
        roonlineprod.nissewaard.nl
        h-i-ambacht.nl
        www.h-i-ambacht.nl
        loket.gemeentemaastricht.nl
        lokalelasten.hollandskroon.nl
        uat.gooisemeren.nl
        lokalelasten.hollandskroon.nl
        afspraken.cgm.nl
        secure.hollandskroon.nl
        intranet.krimpenerwaard.nl
        www.menameradiel.nl
        belastingbalie.dantumadiel.eu
        www.kollumerland.woz-portaal.nl
        intranet.gooisemeren.nl
        secure.cgm.nl
        afspraak.krimpenerwaard.nl
        www.veiligheidshuisregioalkmaar.nl
        gooisemeren.nl
        aalsmeer.notubiz.nl
        alkmaar.notubiz.nl
        dongeradeel.notubiz.nl
        kollumerland.notubiz.nl
        rotterdam.notubiz.nl
        vianen.notubiz.nl
        mail.krimpenerwaard.nl
        webmail.krimpenerwaard.nl
        oostgelre.notubiz.nl
        afspraak.gooisemeren.nl
        mail.gooisemeren.nl
        webmail.gooisemeren.nl
        secure.delft.nl
        parkeren.delft.nl
        www.delft.nl
        zaken.h-i-ambacht.nl
        lokalelasten.hollandskroon.nl
        www.kollumerland.woz-portaal.nl
        secure.cgm.nl
        bestuur.gooisemeren.nl
        woudenberg.nl
        www.woudenberg.nl
        web.schijndel.nl
        afspraken.schinnen.nl
        data.roosendaal.nl
        wozloket.meppel.nl
        parkeren.meppel.nl
        loket.zaltbommel.nl
        afspraken.weert.nl
        parkeren.venlo.nl
        afspraken.laarbeek.nl
        thuiswerken.staphorst.nl
        webservices.rotterdam.nl
        eloket.peelenmaas.nl
        portal.noordoostpolder.nl
        afspraken.montfoort.nl
        afspraken.ijsselstein.nl
        gateway.heerenveen.nl
        extern.huizen.nl
        desktop.heiloo.nl
        desktop.heerhugowaard.nl
        geo.heerenveen.nl
        afspraak.haren.nl
        geo.harderwijk.nl
        afspraken.harderwijk.nl
        afspraken.haaksbergen.nl
        afspraken.gemeentenoordenveld.nl
        ftp.giessenlanden.nl
        afspraak.giessenlanden.nl
        citrix.waalwijk.nl
        seg.zoetermeer.nl
        afspraak.boekel.nl
        citrix.bergenopzoom.nl
        web.aaenhunze.nl
        kaart.almere.nl
        formulieren.venlo.nl
        afspraak.zutphen.nl
        access.zoetermeer.nl
        mag.zoetermeer.nl
        desktop.zoetermeer.nl
        desktop.denhaag.nl
        auth.uden.nl
        afspraken.reimerswaal.nl
        gemeenteraad.hofvantwente.nl
        eloket.heemstede.nl
        loket.oudewater.nl
        opendata.haarlem.nl
        geo.renkum.nl
        loket.heerlen.nl
        ondernemersloket.geldrop-mierlo.nl
        afspraak.nederweert.nl
        intranet.debilt.nl
        toegang.groningen.nl
        archief.heerenveen.nl
        maps.groningen.nl
        gemeente.groningen.nl
        e-loket.vlissingen.nl
        citrix.brielle.nl
        afspraken.veere.nl
        seg.maasdriel.nl
        afspraken.cranendonck.nl
        os.groningen.nl
        eloket.breda.nl
        outlook.meerssen.nl
        extern.amersfoort.nl
        formulieren.hoorn.nl
        digid.arnhem.nl
        extranet.venlo.nl
        ro.emmen.nl
        afspraak.eemsmond.nl
        afspraken.denhelder.nl
        ruimtelijkeplannen.breda.nl
        citrix.dalfsen.nl
        loket.leeuwarden.nl
        auth.schinnen.nl
        thuiswerken.bronckhorst.nl
        afspraken.voerendaal.nl
        afspraken.bronckhorst.nl
        loket.breda.nl
        loket.bloemendaal.nl
        gemeenteraad.vught.nl
        kaart.amsterdam.nl
        stadsarchief.breda.nl
        afspraak.nijkerk.eu
        citrix.hoogeveen.nl
        afspraak.medemblik.nl
        afspraak.waalwijk.nl
        loket.almere.nl
        eloket.hellendoorn.nl
        onlineformulieren.uden.nl
        loket.bergen-nh.nl
        eloket.leusden.nl
        loket.gemeentenoordenveld.nl
        parkeren.haarlemmermeer.nl
        bestuur.zutphen.nl
        eloket.zuidplas.nl
        formulieren.winsum.nl
        formulieren.zuidplas.nl
        afspraak.zederik.nl
        wegwijzer.nijkerk.eu
        toegang.veldhoven.nl
        afspraak.uithoorn.nl
        afspraken.valkenswaard.nl
        bestuur.tubbergen.nl
        afspraken.veendam.nl
        eloket.uden.nl
        access.schijndel.nl
        afspraak.stichtsevecht.nl
        auth.gemeentestein.nl
        afspraken.gemeentestein.nl
        afspraken.steenwijkerland.nl
        afspraken.sonenbreugel.nl
        belastingen.rhenen.nl
        afspraken.nieuwkoop.nl
        afspraken.pekela.nl
        access.peelenmaas.nl
        afspraak.rucphen.nl
        afspraken.purmerend.nl
        afspraken.nuenen.nl
        afspraak.schagen.nl
        loket.neerijnen.nl
        afspraken.assen.nl
        gemeente.lochem.nl
        formulieren.leiderdorp.nl
        belastingen.leeuwarden.nl
        formulieren.kerkrade.nl
        eloket.kerkrade.nl
        loket.gemeentehulst.nl
        gemeente.spijkenisse.nl
        seg.lochem.nl
        belastingen.gemeentewestland.nl
        outlook.heiloo.nl
        diensten.heiloo.nl
        plannen.groningen.nl
        kpn190.lochem.nl
        afspraak.leusden.nl
        www2.venray.nl
        regelingen.lochem.nl
        m.hellendoorn.nl
        kernteam.geldermalsen.nl
        jalp.elburg.nl
        m.enschede.nl
        schatkamers.lochem.nl
        financien.lochem.nl
        m.lochem.nl
        ro.brunssum.nl
        afspraken.brunssum.nl
        rio.lochem.nl
        eloket.lochem.nl
        opendata.alphenaandenrijn.nl
        formulieren.amsterdam.nl
        ruimtelijkeplannen.denhelder.nl
        roonline.lochem.nl
        rekenkamer.lochem.nl
        kc.lochem.nl
        ruimtelijkeplannen.lochem.nl
        lokalelasten.lochem.nl
        kaderbrief.lochem.nl
        roonlineprod.lochem.nl
        extern.lochem.nl
        ro.lochem.nl
        eforms.lochem.nl
        afspraak.oudewater.nl
        afspraak.wijchen.nl
        afspraak.lopik.nl
        opendata.almere.nl
        bestanden.venray.nl
        access.hoorn.nl
        parkeren.almere.nl
        simsite.tynaarlo.nl
        extranet.tholen.nl
        opendata.schiedam.nl
        web1.schiedam.nl
        archief.schiedam.nl
        afspraak.schiedam.nl
        bestanden.schiedam.nl
        parkeren.helmond.nl
        www2.landerd.nl
        afspraak.elburg.nl
        ftp.venray.nl
        kaart.denhaag.nl
        thuiswerk.appingedam.nl
        extranet.waddinxveen.nl
        toerisme.appingedam.nl
        extern.uden.nl
        toegang.appingedam.nl
        roonline.denhaag.nl
        financien.uden.nl
        thuiswerken.appingedam.nl
        eloket.groningen.nl
        seg.woerden.nl
        mag.woerden.nl
        desktop.woerden.nl
        citrix.woerden.nl
        ftp.woensdrecht.nl
        parkeren.hellendoorn.nl
        xziyipt.lochem.nl
        www2.lochem.nl
        wkpb.lochem.nl
        wijkteam.lochem.nl
        wijkprofiel.lochem.nl
        webwerken.lochem.nl
        webservices.lochem.nl
        web.lochem.nl
        verkiezingen.lochem.nl
        uat.lochem.nl
        trainingen.lochem.nl
        toerisme.lochem.nl
        toegang.lochem.nl
        thuiswerken.lochem.nl
        thuiswerk.lochem.nl
        taxatieverslagenwozloket.lochem.nl
        stadsarchief.lochem.nl
        simsite.lochem.nl
        redactie.lochem.nl
        raadsinformatie.lochem.nl
        qwin.lochem.nl
        programmabegroting.lochem.nl
        planonselfservice.lochem.nl
        plannen.lochem.nl
        pki.lochem.nl
        participatiewebshop.lochem.nl
        parkeren.lochem.nl
        outlook.lochem.nl
        os.lochem.nl
        opendata.lochem.nl
        onzeluchtpost.lochem.nl
        oma.lochem.nl
        milieucentrum.lochem.nl
        maps.lochem.nl
        mailcamp.lochem.nl
        mag.lochem.nl
        loket.lochem.nl
        lokalelastenmeter.lochem.nl
        kaart.lochem.nl
        jalp.lochem.nl
        jaarstukken.lochem.nl
        infozuil.lochem.nl
        geo.lochem.nl
        gemeenteraad.lochem.nl
        gemeentebestuur.lochem.nl
        geluid.lochem.nl
        ftp.lochem.nl
        formulieren.lochem.nl
        flexiprint.lochem.nl
        flexinext.lochem.nl
        flexigeo.lochem.nl
        extranet.lochem.nl
        dloket.lochem.nl
        digitalecatalogus.lochem.nl
        digid.lochem.nl
        diensten.lochem.nl
        desktop.lochem.nl
        dacceptatieloket.lochem.nl
        crp.lochem.nl
        concern.lochem.nl
        citrix.lochem.nl
        cars.lochem.nl
        biebcgi.lochem.nl
        beveiligd.lochem.nl
        bestuur.lochem.nl
        bestanden.lochem.nl
        besluitvorming.lochem.nl
        belastingen.lochem.nl
        begroting.lochem.nl
        beeldbank.lochem.nl
        auth.lochem.nl
        archief.lochem.nl
        appl.lochem.nl
        afvalkalender.lochem.nl
        afspraken.lochem.nl
        afspraak.lochem.nl
        aeformsmidoffice.lochem.nl
        access.lochem.nl
        ftp.wijchen.nl
        www2.wierden.nl
        wachtwoord.alkmaar.nl
        gemeente.purmerend.nl
        afspraak.terneuzen.nl
        citrix.nunspeet.nl
        formulieren.lansingerland.nl
        afspraken.ermelo.nl
        formulieren.almere.nl
        kaart.katwijk.nl
        gemeenteraad.westvoorne.nl
        digid.weststellingwerf.nl
        dloket.gemeentewestland.nl
        dacceptatieloket.gemeentewestland.nl
        simsite.westervoort.nl
        diensten.westmaasenwaal.nl
        raad.werkendam.nl
        intranet.werkendam.nl
        belastingen.bunschoten.nl
        citrix.werkendam.nl
        beveiligd.werkendam.nl
        bestuur.werkendam.nl
        archief.werkendam.nl
        loket.beuningen.nl
        ro.schijndel.nl
        afspraken.schijndel.nl
        afspraak.winsum.nl
        web.gorinchem.nl
        gemeente.almere.nl
        jalp.oldebroek.nl
        afspraken.amersfoort.nl
        simsite.cranendonck.nl
        plannen.almere.nl
        m.utrecht.nl
        loket.tiel.nl
        www2.wageningen.nl
        web01.wageningen.nl
        ruimtelijkeplannen.wageningen.nl
        raadsinformatie.wageningen.nl
        simsite.waalre.nl
        extranet.waalre.nl
        archief.waalre.nl
        afvalkalender.waalre.nl
        loket.heerhugowaard.nl
        opendata.voorst.nl
        m.voorst.nl
        ro.vlissingen.nl
        geo.vlissingen.nl
        extranet.vlieland.nl
        bestuur.vlieland.nl
        ftp.vlaardingen.nl
        extranet.vlaardingen.nl
        pki.vianen.nl
        geo.vianen.nl
        ruimtelijkeplannen.venray.nl
        geo.venray.nl
        afvalkalender.venray.nl
        ruimtelijkeplannen.venlo.nl
        maps.venlo.nl
        gemeenteraad.venlo.nl
        ftp.venlo.nl
        begroting.venlo.nl
        archief.venlo.nl
        opendata.velsen.nl
        parkeren.veldhoven.nl
        afvalkalender.veldhoven.nl
        ro.veghel.nl
        m.veghel.nl
        loket.veere.nl
        web.veenendaal.nl
        geo.veenendaal.nl
        ftp.veenendaal.nl
        gemeente.veendam.nl
        ftp.veendam.nl
        dacceptatieloket.veendam.nl
        besluitvorming.veendam.nl
        afspraak.veendam.nl
        geo.valkenswaard.nl
        ftp.valkenswaard.nl
        toerisme.valkenburg.nl
        ro.valkenburg.nl
        gemeente.valkenburg.nl
        ro.vaals.nl
        oma.heuvelrug.nl
        ftp.heuvelrug.nl
        extranet.heuvelrug.nl
        cars.heuvelrug.nl
        rekenkamer.utrecht.nl
        diensten.utrecht.nl
        thuiswerken.urk.nl
        redactie.uithoorn.nl
        digid.uithoorn.nl
        desktop.uithoorn.nl
        eloket.uitgeest.nl
        formulieren.tynaarlo.nl
        www2.tilburg.nl
        verkiezingen.tilburg.nl
        ruimtelijkeplannen.tilburg.nl
        opendata.tilburg.nl
        loket.tilburg.nl
        kaart.tilburg.nl
        ftp.tilburg.nl
        extranet.tilburg.nl
        beeldbank.tilburg.nl
        afspraken.waddinxveen.nl
        kaart.tiel.nl
        portal.utrecht.nl
        ftp.tholen.nl
        extranet.terneuzen.nl
        beheer.terneuzen.nl
        plannen.staphorst.nl
        loket.hofvantwente.nl
        afspraken.hofvantwente.nl
        archief.stadskanaal.nl
        digid.dronten.nl
        ruimtelijkeplannen.sonenbreugel.nl
        formulieren.demarne.nl
        afspraak.derondevenen.nl
        ftp.sonenbreugel.nl
        plannen.someren.nl
        ftp.schinnen.nl
        digid.schiermonnikoog.nl
        beeldbank.schiedam.nl
        www2.maasdonk.nl
        gemeente.rucphen.nl
        www2.rotterdam.nl
        beeldbank.rotterdam.nl
        web.roosendaal.nl
        ftp.denhelder.nl
        kaart.roosendaal.nl
        ftp.roosendaal.nl
        ftp.rijswijk.nl
        belastingen.rijswijk.nl
        raadsinformatie.ridderkerk.nl
        simsite.rhenen.nl
        ftp.rheden.nl
        ro.reimerswaal.nl
        geo.reimerswaal.nl
        verkiezingen.putten.nl
        loket.putten.nl
        eloket.putten.nl
        cars.purmerend.nl
        archief.purmerend.nl
        dacceptatieloket.pekela.nl
        afspraak.pekela.nl
        afvalkalender.peelenmaas.nl
        loket.overbetuwe.nl
        simsite.oudewater.nl
        financien.oss.nl
        begroting.oss.nl
        ruimtelijkeplannen.opsterland.nl
        ftp.opsterland.nl
        archief.oostzaan.nl
        afspraken.oostzaan.nl
        financien.ooststellingwerf.nl
        digid.ooststellingwerf.nl
        begroting.ooststellingwerf.nl
        ruimtelijkeplannen.oostgelre.nl
        ruimtelijkeplannen.oldenzaal.nl
        loket.oldenzaal.nl
        ftp.oirschot.nl
        extranet.oirschot.nl
        afspraken.oirschot.nl
        www2.oegstgeest.nl
        regelingen.oegstgeest.nl
        raadsinformatie.oegstgeest.nl
        gemeenteraad.oegstgeest.nl
        afspraken.oegstgeest.nl
        ftp.nuth.nl
        www2.nunspeet.nl
        m.nunspeet.nl
        geo.nunspeet.nl
        ftp.nunspeet.nl
        ruimtelijkeplannen.nuenen.nl
        ftp.nuenen.nl
        afvalkalender.nuenen.nl
        ruimtelijkeplannen.noordoostpolder.nl
        ftp.noordoostpolder.nl
        dloket.noordoostpolder.nl
        dacceptatieloket.noordoostpolder.nl
        archief.gemeentenoordenveld.nl
        planonselfservice.spijkenisse.nl
        loket.spijkenisse.nl
        geo.spijkenisse.nl
        formulieren.spijkenisse.nl
        eforms.spijkenisse.nl
        www2.nijmegen.nl
        ruimtelijkeplannen.nijmegen.nl
        parkeren.nijmegen.nl
        m.nijmegen.nl
        kaart.nijmegen.nl
        ftp.nijmegen.nl
        extranet.nijmegen.nl
        begroting.nijmegen.nl
        m.nieuwkoop.nl
        extranet.nieuwkoop.nl
        maps.neerijnen.nl
        afspraak.neerijnen.nl
        web.nederweert.nl
        loket.mookenmiddelaar.nl
        loket.montfoort.nl
        extranet.montfoort.nl
        archief.gemeentemolenwaard.nl
        geo.moerdijk.nl
        ftp.moerdijk.nl
        ro.middelburg.nl
        ftp.middelburg.nl
        ruimtelijkeplannen.meppel.nl
        formulieren.dongen.nl
        ftp.menterwolde.nl
        dloket.menterwolde.nl
        dacceptatieloket.menterwolde.nl
        citrix.menterwolde.nl
        cars.medemblik.nl
        rproxy21.maastricht.nl
        rproxy20.maastricht.nl
        loket.gemeentemaasgouw.nl
        geo.gemeentemaasgouw.nl
        ftp.gemeentemaasgouw.nl
        extranet.gemeentemaasgouw.nl
        loket.maasdriel.nl
        citrix.losser.nl
        ftp.lopik.nl
        ruimtelijkeplannen.lingewaal.nl
        afspraak.lingewaal.nl
        loket.leusden.nl
        ftp.leusden.nl
        formulieren.leusden.nl
        digid.leusden.nl
        www2.leudal.nl
        programmabegroting.leiderdorp.nl
        afspraken.leiderdorp.nl
        seg.leudal.nl
        bestuur.gemeentelangedijk.nl
        gemeenteraad.haarlemmermeer.nl
        gemeentebestuur.haarlem.nl
        bestuur.goirle.nl
        loket.dronten.nl
        besluitvorming.doetinchem.nl
        gemeenteraad.denhelder.nl
        besluitvorming.demarne.nl
        besluitvorming.wormerland.nl
        bestuur.winsum.nl
        gemeenteraad.weert.nl
        bestuur.weert.nl
        bestuur.vaals.nl
        citrix.simpelveld.nl
        gemeenteraad.oudewater.nl
        besluitvorming.oostzaan.nl
        afspraak.krimpenaandenijssel.nl
        raadsinformatie.kerkrade.nl
        gemeenteraad.bloemendaal.nl
        formulieren.bedum.nl
        besluitvorming.bedum.nl
        loket.asten.nl
        kaart.leiden.nl
        gemeente.leiden.nl
        plannen.leeuwarderadeel.nl
        ftp.leeuwarderadeel.nl
        outlook.hoogeveen.nl
        digid.leeuwarderadeel.nl
        parkeren.leeuwarden.nl
        geo.buren.nl
        opendata.leeuwarden.nl
        m.leeuwarden.nl
        geo.leeuwarden.nl
        frege.leeuwarden.nl
        amsterdam.leeuwarden.nl
        geo.leerdam.nl
        ftp.laren.nl
        extranet.laren.nl
        dloket.laren.nl
        dacceptatieloket.laren.nl
        rekenkamer.lansingerland.nl
        ftp.lansingerland.nl
        ro.gemeentelangedijk.nl
        loket.gemeentelangedijk.nl
        formulieren.landsmeer.nl
        m.landerd.nl
        simsite.ouderkerk.nl
        simsite.nederlek.nl
        simsite.gemeentevlist.nl
        simsite.bergambacht.nl
        belastingen.mookenmiddelaar.nl
        pki.gemeentevlist.nl
        ftp.schoonhoven.nl
        ftp.nederlek.nl
        ftp.gemeentevlist.nl
        ftp.bergambacht.nl
        extranet.nederlek.nl
        eloket.krimpenaandenijssel.nl
        cars.koggenland.nl
        ro.kerkrade.nl
        loket.kerkrade.nl
        ruimtelijkeplannen.katwijk.nl
        verkiezingen.kapelle.nl
        gemeente.kapelle.nl
        gemeente.kampen.nl
        archief.kampen.nl
        loket.ijsselstein.nl
        extranet.ijsselstein.nl
        web.gemeentehulst.nl
        extranet.gemeentehulst.nl
        geo.huizen.nl
        geo.horstaandemaas.nl
        loket.hoorn.nl
        gemeente.hoogeveen.nl
        ftp.hoogeveen.nl
        werkplek.alkmaar.nl
        beeldbank.hoogeveen.nl
        ftp.hofvantwente.nl
        ruimtelijkeplannen.hillegom.nl
        m.hillegom.nl
        loket.heusden.nl
        afspraak.heusden.nl
        pki.heumen.nl
        plannen.hetbildt.nl
        digid.hetbildt.nl
        loket.hengelo.nl
        m.helmond.nl
        loket.helmond.nl
        geo.helmond.nl
        ftp.helmond.nl
        ftp.heerlen.nl
        ruimtelijkeplannen.heerhugowaard.nl
        plannen.heerenveen.nl
        m.heerenveen.nl
        loket.heerde.nl
        ftp.heemstede.nl
        begroting.heemstede.nl
        loket.hattem.nl
        ftp.hattem.nl
        simsite.epe.nl
        toegang.haren.nl
        thuiswerken.haren.nl
        archief.haren.nl
        ruimtelijkeplannen.harderwijk.nl
        ro.hardenberg.nl
        loket.hardenberg.nl
        geo.hardenberg.nl
        archief.hardenberg.nl
        afspraak.halderberge.nl
        web.haarlemmermeer.nl
        uat.haarlemmermeer.nl
        m.haarlemmermeer.nl
        www2.groningen.nl
        toerisme.groningen.nl
        m.groningen.nl
        begroting.groningen.nl
        ruimtelijkeplannen.gorinchem.nl
        ftp.gorinchem.nl
        afspraken.gorinchem.nl
        webservices.goirle.nl
        ruimtelijkeplannen.goirle.nl
        afvalkalender.goes.nl
        ftp.gilzerijen.nl
        extranet.gilzerijen.nl
        dloket.gilzerijen.nl
        dacceptatieloket.gilzerijen.nl
        ftp.gennep.nl
        afspraken.gennep.nl
        wijkteam.geldermalsen.nl
        ruimtelijkeplannen.geldermalsen.nl
        jalp.geldermalsen.nl
        plannen.ferwerderadiel.nl
        digid.ferwerderadiel.nl
        ruimtelijkeplannen.ermelo.nl
        verkiezingen.enschede.nl
        stadsarchief.enschede.nl
        ruimtelijkeplannen.enschede.nl
        programmabegroting.enschede.nl
        loket.enschede.nl
        ftp.enschede.nl
        formulieren.enschede.nl
        eloket.enschede.nl
        citrix.enschede.nl
        pki.enkhuizen.nl
        www2.emmen.nl
        loket.emmen.nl
        geo.emmen.nl
        extern.emmen.nl
        www2.eindhoven.nl
        afspraken.goes.nl
        ftp.eindhoven.nl
        afvalkalender.eindhoven.nl
        extranet.eersel.nl
        afspraken.eersel.nl
        parkeren.amsterdam.nl
        dacceptatieloket.eemnes.nl
        simsite.zeevang.nl
        pki.zeevang.nl
        ruimtelijkeplannen.dronten.nl
        pki.dronten.nl
        gemeenteraad.dronten.nl
        pki.drimmelen.nl
        verkiezingen.dongeradeel.nl
        ruimtelijkeplannen.dongeradeel.nl
        geo.dongeradeel.nl
        cars.dongeradeel.nl
        wkpb.dongen.nl
        webservices.dongen.nl
        pki.doetinchem.nl
        ftp.doetinchem.nl
        archief.doetinchem.nl
        ro.doesburg.nl
        simsite.dinkelland.nl
        toegang.deurne.nl
        pki.deurne.nl
        oma.deurne.nl
        ftp.deurne.nl
        afvalkalender.deurne.nl
        extranet.denhelder.nl
        bestuur.denhelder.nl
        digid.denhaag.nl
        appl.denhaag.nl
        afspraken.delfzijl.nl
        ftp.dewolden.nl
        extranet.derondevenen.nl
        www2.debilt.nl
        wkpb.debilt.nl
        ruimtelijkeplannen.debilt.nl
        afspraak.debilt.nl
        diensten.dantumadeel.nl
        citrix.dantumadeel.nl
        ro.dalfsen.nl
        formulieren.dalfsen.nl
        financien.dalfsen.nl
        begroting.dalfsen.nl
        outlook.cuijk.nl
        bestuur.cuijk.nl
        afvalkalender.cranendonck.nl
        www2.coevorden.nl
        loket.coevorden.nl
        www2.capelleaandenijssel.nl
        kaart.capelleaandenijssel.nl
        formulieren.capelleaandenijssel.nl
        ruimtelijkeplannen.brummen.nl
        ftp.brummen.nl
        ruimtelijkeplannen.bronckhorst.nl
        programmabegroting.bronckhorst.nl
        jaarstukken.bronckhorst.nl
        ftp.bronckhorst.nl
        www2.breda.nl
        rekenkamer.breda.nl
        beeldbank.breda.nl
        loket.borne.nl
        webserver03.bloemendaal.nl
        formulieren.wijchen.nl
        www2.waalre.nl
        dloket.blaricum.nl
        dacceptatieloket.blaricum.nl
        pki.binnenmaas.nl
        formulieren.stichtsevecht.nl
        ftp.beverwijk.nl
        gemeentebestuur.beuningen.nl
        ares.beuningen.nl
        www2.gemeentebest.nl
        afspraken.bernheze.org
        ro.gemeenteberkelland.nl
        afvalkalender.gemeenteberkelland.nl
        extranet.bergen.nl
        ris.bergeijk.nl
        intranet.bergeijk.nl
        afspraken.bergeijk.nl
        ruimtelijkeplannen.groesbeek.nl
        afspraak.groesbeek.nl
        ftp.bellingwedde.nl
        extranet.beesel.nl
        eforms.beesel.nl
        simsite.beemster.net
        pki.beemster.net
        ftp.gemeentebeek.nl
        rekenkamer.barendrecht.nl
        afspraak.barendrecht.nl
        extranet.baarn.nl
        web.asten.nl
        plannen.asten.nl
        www2.arnhem.nl
        loket.arnhem.nl
        geo.arnhem.nl
        financien.arnhem.nl
        begroting.arnhem.nl
        xziyipt.appingedam.nl
        www2.appingedam.nl
        wkpb.appingedam.nl
        wijkteam.appingedam.nl
        wijkprofiel.appingedam.nl
        webwerken.appingedam.nl
        webservices.appingedam.nl
        web.appingedam.nl
        verkiezingen.appingedam.nl
        uat.appingedam.nl
        trainingen.appingedam.nl
        taxatieverslagenwozloket.appingedam.nl
        stadsarchief.appingedam.nl
        seg.appingedam.nl
        schatkamers.appingedam.nl
        ruimtelijkeplannen.appingedam.nl
        roonlineprod.appingedam.nl
        roonline.appingedam.nl
        ro.appingedam.nl
        rio.appingedam.nl
        rekenkamer.appingedam.nl
        regelingen.appingedam.nl
        redactie.appingedam.nl
        raadsinformatie.appingedam.nl
        qwin.appingedam.nl
        programmabegroting.appingedam.nl
        planonselfservice.appingedam.nl
        plannen.appingedam.nl
        pki.appingedam.nl
        participatiewebshop.appingedam.nl
        parkeren.appingedam.nl
        outlook.appingedam.nl
        os.appingedam.nl
        opendata.appingedam.nl
        onzeluchtpost.appingedam.nl
        onlineformulieren.appingedam.nl
        oma.appingedam.nl
        mx10.appingedam.nl
        milieucentrum.appingedam.nl
        mijntexel.appingedam.nl
        maps.appingedam.nl
        mailcamp.appingedam.nl
        mag.appingedam.nl
        m.appingedam.nl
        loket.appingedam.nl
        lokalelastenmeter.appingedam.nl
        lokalelasten.appingedam.nl
        kpn190.appingedam.nl
        kc.appingedam.nl
        kaderbrief.appingedam.nl
        kaart.appingedam.nl
        jalp.appingedam.nl
        jaarstukken.appingedam.nl
        infozuil.appingedam.nl
        geo.appingedam.nl
        gemeenteraad.appingedam.nl
        gemeentebestuur.appingedam.nl
        gemeente.appingedam.nl
        geluid.appingedam.nl
        ftp.appingedam.nl
        formulieren.appingedam.nl
        flexiprint.appingedam.nl
        flexinext.appingedam.nl
        flexigeo.appingedam.nl
        financien.appingedam.nl
        extranet.appingedam.nl
        extern.appingedam.nl
        dloket.laarbeek.nl
        eloket.appingedam.nl
        eforms.appingedam.nl
        dloket.appingedam.nl
        digitalecatalogus.appingedam.nl
        digid.appingedam.nl
        diensten.appingedam.nl
        desktop.appingedam.nl
        dloket.olst-wijhe.nl
        dloket.gemeente-oldambt.nl
        mail.haarlemmerliede.nl
        dacceptatieloket.appingedam.nl
        crp.appingedam.nl
        concern.appingedam.nl
        citrix.appingedam.nl
        cars.appingedam.nl
        biebcgi.appingedam.nl
        beveiligd.appingedam.nl
        bestuur.appingedam.nl
        bestanden.appingedam.nl
        besluitvorming.appingedam.nl
        belastingen.appingedam.nl
        begroting.appingedam.nl
        beeldbank.appingedam.nl
        auth.appingedam.nl
        dloket.landsmeer.nl
        dacceptatieloket.landsmeer.nl
        dloket.landerd.nl
        dacceptatieloket.landerd.nl
        formulieren.krimpenaandenijssel.nl
        dloket.kampen.nl
        dacceptatieloket.kampen.nl
        archief.appingedam.nl
        appl.appingedam.nl
        afvalkalender.appingedam.nl
        dacceptatieloket.helmond.nl
        dloket.hellendoorn.nl
        dacceptatieloket.hellendoorn.nl
        dloket.groningen.nl
        dacceptatieloket.groningen.nl
        dloket.hardenberg.nl
        afspraken.appingedam.nl
        afspraak.appingedam.nl
        aeformsmidoffice.appingedam.nl
        dacceptatieloket.emmen.nl
        access.appingedam.nl
        begroting.apeldoorn.nl
        rekenkamer.amsterdam.nl
        dloket.coevorden.nl
        dacceptatieloket.coevorden.nl
        dloket.bellingwedde.nl
        dacceptatieloket.bellingwedde.nl
        os.amsterdam.nl
        onderhoudspagina.amsterdam.nl
        maps.amsterdam.nl
        stadsarchief.amsterdam.nl
        m.amsterdam.nl
        loket.amsterdam.nl
        gemeente.amsterdam.nl
        ftp.amsterdam.nl
        beeldbank.amsterdam.nl
        redactie.amstelveen.nl
        parkeren.amstelveen.nl
        geo.amstelveen.nl
        bestuur.amstelveen.nl
        m.amersfoort.nl
        formulieren.amersfoort.nl
        formulieren.alphenaandenrijn.nl
        afvalkalender.alphenaandenrijn.nl
        access.alphenaandenrijn.nl
        citrix.almere.nl
        simsite.almelo.nl
        ruimtelijkeplannen.almelo.nl
        gemeenteraad.alkmaar.nl
        simsite.achtkarspelen.nl
        ruimtelijkeplannen.achtkarspelen.nl
        ftp.achtkarspelen.nl
        toegang.aalten.nl
        redactie.aalsmeer.nl
        bestuur.aalsmeer.nl
        www2.aaenhunze.nl
        loket.aaenhunze.nl
        geo.aaenhunze.nl
        kaart.uden.nl
        thuiswerken.veghel.nl
        gemeentearchief.amsterdam.nl
        data.amsterdam.nl
        support.zandvoort.nl
        access.s-hertogenbosch.nl
        belastingbalie.noordoostpolder.nl
        gemeenteraad.assen.nl
        outlook.beesel.nl
        afspraken.beesel.nl
        gemeentebestuur.leusden.nl
        dacceptatieloket.hardenberg.nl
        simsite.gennep.nl
        extranet.gennep.nl
        afspraken.almelo.nl
        www.loket.enschede.nl
        secure.scherpenzeel.nl
        simsite.zuidplas.nl
        extranet.zuidplas.nl
        simsite.zuidhorn.nl
        simsite.zoeterwoude.nl
        simsite.zoetermeer.nl
        simsite.zeewolde.nl
        simsite.wijchen.nl
        simsite.wierden.nl
        simsite.westvoorne.nl
        simsite.weststellingwerf.nl
        loket.gemeentewestland.nl
        secure.nijkerk.eu
        gemeentewinkel.korendijk.nl
        simsite.westmaasenwaal.nl
        simsite.weesp.nl
        loket.waalwijk.nl
        simsite.voerendaal.nl
        extranet.voerendaal.nl
        simsite.waddinxveen.nl
        bestuur.veghel.nl
        simsite.veere.nl
        extranet.veere.nl
        simsite.veendam.nl
        extranet.valkenswaard.nl
        simsite.valkenburg.nl
        extranet.valkenburg.nl
        simsite.vaals.nl
        simsite.heuvelrug.nl
        simsite.stichtsevecht.nl
        loket.stichtsevecht.nl
        simsite.staphorst.nl
        simsite.sintanthonis.nl
        extranet.sintanthonis.nl
        simsite.simpelveld.nl
        simsite.schinnen.nl
        wijkteam.schagen.nl
        simsite.schagen.nl
        simsite.opmeer.nl
        extranet.opmeer.nl
        simsite.ooststellingwerf.nl
        simsite.onderbanken.nl
        simsite.oirschot.nl
        simsite.nuth.nl
        simsite.nunspeet.nl
        simsite.noordwijk.nl
        simsite.nieuwkoop.nl
        simsite.mookenmiddelaar.nl
        simsite.middendelfland.nl
        simsite.menterwolde.nl
        extranet.menterwolde.nl
        simsite.gemeentemaasgouw.nl
        simsite.loppersum.nl
        simsite.lingewaal.nl
        simsite.leudal.nl
        simsite.landgraaf.nl
        eforms.landgraaf.nl
        simsite.kapelle.nl
        extranet.kapelle.nl
        simsite.huizen.nl
        simsite.hilvarenbeek.nl
        simsite.heumen.nl
        simsite.haren.nl
        extranet.haren.nl
        simsite.harderwijk.nl
        simsite.haaren.nl
        simsite.grave.nl
        simsite.gorinchem.nl
        simsite.gilzerijen.nl
        simsite.giessenlanden.nl
        extranet.giessenlanden.nl
        simsite.ermelo.nl
        simsite.eindhoven.nl
        afspraken.eindhoven.nl
        simsite.eersel.nl
        simsite.eemsmond.nl
        simsite.druten.nl
        extranet.druten.nl
        simsite.dronten.nl
        simsite.doesburg.nl
        loket.dinkelland.nl
        simsite.deurne.nl
        simsite.delfzijl.nl
        simsite.derondevenen.nl
        simsite.cuijk.nl
        simsite.cromstrijen.nl
        simsite.bunschoten.nl
        extranet.deurne.nl
        simsite.bronckhorst.nl
        extranet.bronckhorst.nl
        simsite.brielle.nl
        extranet.brielle.nl
        simsite.breda.nl
        formulieren.breda.nl
        simsite.borsele.nl
        simsite.boekel.nl
        simsite.binnenmaas.nl
        simsite.beverwijk.nl
        simsite.bergeijk.nl
        simsite.groesbeek.nl
        extranet.bellingwedde.nl
        simsite.gemeentebeek.nl
        extranet.gemeentebeek.nl
        simsite.baarn.nl
        simsite.appingedam.nl
        simsite.aalten.nl
        secure.edam-volendam.nl
        simsite.nijkerk.eu
        loket.veenendaal.nl
        portal.leiden.nl
        dloket.enschede.nl
        dacceptatieloket.enschede.nl
        webservices.tilburg.nl
        bestuur.debilt.nl
        dacceptatieloket.zwolle.nl
        dacceptatieloket.velsen.nl
        dacceptatieloket.schijndel.nl
        eloket.moerdijk.nl
        ro.zwolle.nl
        loket.zwolle.nl
        ftp.zwolle.nl
        web.zwartewaterland.nl
        pki.zwartewaterland.nl
        ftp.zundert.nl
        ftp.zuidhorn.nl
        afvalkalender.zuidhorn.nl
        pki.zoeterwoude.nl
        m.zoetermeer.nl
        ftp.zoetermeer.nl
        simsite.zevenaar.nl
        webwerken.zeist.nl
        ftp.zeist.nl
        archief.zeist.nl
        ruimtelijkeplannen.zeewolde.nl
        pki.zeewolde.nl
        ruimtelijkeplannen.zaltbommel.nl
        gemeenteraad.zaltbommel.nl
        eforms.moerdijk.nl
        ftp.wormerland.nl
        archief.wormerland.nl
        afspraken.wormerland.nl
        eloket.wijdemeren.nl
        roonline.westvoorne.nl
        ftp.werkendam.nl
        toerisme.weert.nl
        gemeente.weert.nl
        ftp.wassenaar.nl
        ftp.voorschoten.nl
        citrix.moerdijk.nl
        mijntexel.lochem.nl
        secure.tiel.nl
        loket.roosendaal.nl
        ftp.reimerswaal.nl
        opendata.purmerend.nl
        loket.purmerend.nl
        afspraak.peelenmaas.nl
        auth.waddinxveen.nl
        auth.rucphen.nl
        afspraken.meerssen.nl
        parkeren.leiden.nl
        geo.koggenland.nl
        gemeente.doetinchem.nl
        afspraken.zevenaar.nl
        afspraken.westervoort.nl
        m.haarlem.nl
        afspraken.stadskanaal.nl
        afspraken.sintanthonis.nl
        loket.oss.nl
        simsite.naarden.nl
        ro.naarden.nl
        extranet.naarden.nl
        afspraak.gemeentehulst.nl
        loket.bunnik.nl
        citrix.gemeentebeek.nl
        m.eindhoven.nl
        loket.eindhoven.nl
        gemeente.eindhoven.nl
        beeldbank.eindhoven.nl
        afspraak.deurne.nl
        m.bloemendaal.nl
        web.staphorst.nl
        simsite.schermer.nl
        simsite.graftderijp.nl
        extranet.graftderijp.nl
        extranet.alkmaar.nl
        gemeenteraad.vlissingen.nl
        gemeenteraad.almere.nl
        ftp.vlissingen.nl
        bestuur.gemeentenoordenveld.nl
        toegang.eindhoven.nl
        thuiswerken.middendelfland.nl
        bestanden.doetinchem.nl
        afspraken.zwolle.nl
        extern.vught.nl
        desktop.gemeentestein.nl
        afspraken.druten.nl
        afspraak.zaltbommel.nl
        ruimtelijkeplannen.vlagtwedde.nl
        ruimtelijkeplannen.stadskanaal.nl
        diensten.purmerend.nl
        loket.oostgelre.nl
        afspraak.gemeentebest.nl
        citrix.maassluis.nl
        ftp.hardenberg.nl
        simsite.doetinchem.nl
        afspraken.capelleaandenijssel.nl
        simsite.buren.nl
        secure.culemborg.nl
        outlook.denhaag.nl
        archief.denhaag.nl
        afspraken.denhaag.nl
        afspraken.zuidplas.nl
        bestanden.lansingerland.nl
        www2.haarlemmermeer.nl
        citrix.dongeradeel.nl
        simsite.koggenland.nl
        onlineformulieren.lochem.nl
        mx10.lochem.nl
        thuiswerken.hillegom.nl
        dloket.helmond.nl
        auth.zuidplas.nl
        afspraak.middendrenthe.nl
        afspraken.brummen.nl
        simsite.bernheze.org
        simsite.bellingwedde.nl
        afspraak.nijmegen.nl
        simsite.heiloo.nl
        simsite.valkenswaard.nl
        webmail.rucphen.nl
        eloket.rucphen.nl
        simsite.rotterdam.nl
        simsite.roerdalen.nl
        simsite.ridderkerk.nl
        simsite.reuseldemierden.nl
        extranet.renswoude.nl
        simsite.reimerswaal.nl
        simsite.pekela.nl
        auth.gouda.nl
        afspraak.drimmelen.nl
        simsite.bergen.nl
        dloket.zwolle.nl
        ro.zwijndrecht.nl
        afspraak.zwijndrecht.nl
        afspraken.vlissingen.nl
        portal.vlaardingen.nl
        geo.vlaardingen.nl
        dloket.velsen.nl
        geo.veghel.nl
        gemeenteraad.veenendaal.nl
        dloket.veendam.nl
        cars.tynaarlo.nl
        afspraken.tynaarlo.nl
        ro.sliedrecht.nl
        loket.sliedrecht.nl
        ftp.sliedrecht.nl
        dloket.schijndel.nl
        geo.schagen.nl
        toegang.rotterdam.nl
        dloket.rotterdam.nl
        dacceptatieloket.rotterdam.nl
        citrix.roosendaal.nl
        dloket.pekela.nl
        ro.papendrecht.nl
        dloket.oostgelre.nl
        dacceptatieloket.oostgelre.nl
        bestanden.oostgelre.nl
        dacceptatieloket.oldenzaal.nl
        afspraken.oisterwijk.nl
        opendata.nijmegen.nl
        afspraken.nijmegen.nl
        ftp.montfoort.nl
        afspraak.maassluis.nl
        afspraak.maasdriel.nl
        eforms.krimpenaandenijssel.nl
        ftp.ijsselstein.nl
        web.annapaulowna.nl
        ftp.annapaulowna.nl
        afspraak.heumen.nl
        gemeenteraad.gorinchem.nl
        afspraken.goirle.nl
        archief.eindhoven.nl
        ro.dordrecht.nl
        afspraken.diemen.nl
        ftp.demarne.nl
        afspraken.dalfsen.nl
        eloket.capelleaandenijssel.nl
        access.capelleaandenijssel.nl
        opendata.arnhem.nl
        ro.alblasserdam.nl
        loket.alblasserdam.nl
        """

        aa = extra_urls.split('\n')
        bb = []
        for a in aa:
            clean = a.strip()
            if clean:
                bb.append(clean)

        # print(bb)

        s = ScannerTlsQualys()
        s.scan(bb)

        dr = DetermineRatings()
        dr.rate_urls()
        dr.rate_organizations()

        print("Done, scanned all!")
