# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:04
from __future__ import unicode_literals

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fail", "0004_auto_20170222_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
