# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fail", "0005_auto_20170222_1955"),
        ("fail", "0005_auto_20170222_1904"),
    ]

    operations = []
