# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fail", "0006_merge_20170222_2000"),
        ("fail", "0007_auto_20170222_2008"),
    ]

    operations = []
