# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fail', '0009_auto_20170222_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.DeleteModel(
            name='ScansDnssec',
        ),
        migrations.DeleteModel(
            name='ScansSsllabs',
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='url',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
