# Generated by Django 2.0.3 on 2018-04-04 19:08

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='organization_address_geocoded',
            field=djgeojson.fields.GeoJSONField(
                blank=True, help_text='Automatic geocoded organization address.', max_length=5000, null=True),
        ),
    ]
