# Generated by Django 2.0.7 on 2018-08-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20180806_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubmission',
            name='has_been_accepted',
            field=models.BooleanField(
                db_index=True, default=False, help_text='If the admin likes it, they can accept the submission to be part of the real system'),
        ),
        migrations.AlterField(
            model_name='organizationsubmission',
            name='has_been_rejected',
            field=models.BooleanField(db_index=True, default=False,
                                      help_text='Nonsense organizations can be rejected.'),
        ),
        migrations.AlterField(
            model_name='urlsubmission',
            name='has_been_accepted',
            field=models.BooleanField(
                db_index=True, default=False, help_text='If the admin likes it, they can accept the submission to be part of the real system'),
        ),
        migrations.AlterField(
            model_name='urlsubmission',
            name='has_been_rejected',
            field=models.BooleanField(db_index=True, default=False,
                                      help_text='Rejected urls makes for deduction in points.'),
        ),
    ]
