# Generated by Django 2.1.3 on 2018-12-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_contest_url_organization_discovery_help"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="logo_filename",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="website",
        ),
        migrations.AddField(
            model_name="organizationsubmission",
            name="suggested_urls",
            field=models.TextField(
                blank=True,
                help_text="A set of or urls, comma separated that can be added when the organization was approved.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="name",
            field=models.CharField(
                help_text="Name of the contest, might be abbreviated, don't use long words.",
                max_length=42,
                verbose_name="Contest name",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="url_organization_discovery_help",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTML: information where contestants can find good sources of urls / organizations. Displayed on both the URL and Organization adding forms.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
