# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_scansbla'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansbla',
            name='state',
            field=models.CharField(default='PENDING', max_length=64),
        ),
        migrations.AddField(
            model_name='scansbla',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scansbla',
            name='rating',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
