# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0009_endpoint_discovered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='discovered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
