# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_url_created_on'),
        ('scanners', '0010_auto_20170911_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Used when there is no known URL.', max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('width_pixels', models.IntegerField(default=0)),
                ('height_pixels', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.Url')),
            ],
        ),
    ]
