# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0012_auto_20170913_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='server_name',
            field=models.CharField(blank=True, help_text='rdns, gift from the scan, deprecated', max_length=255),
        ),
        migrations.AlterField(
            model_name='tlsqualysscan',
            name='pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
