# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20171017_1317'),
        ('scanners', '0022_auto_20171030_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointip',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Url'),
        ),
    ]
