# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0025_auto_20171030_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='discovered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
