# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0029_auto_20171113_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='server_name',
        ),
    ]
