# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0026_auto_20171110_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='is_dead',
            field=models.BooleanField(
                default=False, help_text='If the port is closed, or the endpoint is otherwisenot reachable over the specified protocol, then markit as dead. A scanner for this port/protocol can alsodeclare it dead. This port is closed on this protocol.'),
        ),
    ]
