# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 16:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_auto_20180208_1318'),
        ('scanners', '0033_auto_20180301_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGenericScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True,
                                          help_text='The type of scan that was performed. Instead of having different tables for eachscan, this label separates the scans.', max_length=60)),
                ('rating', models.CharField(
                    default=0, help_text="Preferably an integer, 'True' or 'False'. Keep ratings over time consistent.", max_length=6)),
                ('explanation', models.CharField(default=0,
                                                 help_text='Short explanation from the scanner on how the rating came to be.', max_length=255)),
                ('evidence', models.CharField(default=0, help_text='Content that might help understanding the result.', max_length=9001)),
                ('last_scan_moment', models.DateTimeField(auto_now_add=True, db_index=True,
                                                          help_text='This gets updated when all the other fields stay the same. If one changes, anew scan will be saved, obsoleting the older ones.')),
                ('rating_determined_on', models.DateTimeField(
                    help_text="This is when the current rating was first discovered. It may be obsoleted byanother rating or explanation (which might have the same rating). This date cannot change once it's set.")),
                ('domain', models.CharField(help_text='Deprecated', max_length=255)),
                ('url', models.ForeignKey(blank=True, null=True,
                                          on_delete=django.db.models.deletion.CASCADE, to='organizations.Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='endpointgenericscan',
            name='evidence',
            field=models.CharField(
                default=0, help_text='Content that might help understanding the result.', max_length=9001),
        ),
        migrations.AlterField(
            model_name='endpointgenericscan',
            name='domain',
            field=models.CharField(help_text='Deprecated', max_length=255),
        ),
        migrations.AlterField(
            model_name='endpointgenericscan',
            name='explanation',
            field=models.CharField(
                default=0, help_text='Short explanation from the scanner on how the rating came to be.', max_length=255),
        ),
    ]
