# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0032_auto_20180119_1144'),
        ('scanners', '0036_auto_20180302_1741'),
    ]

    operations = [
    ]
