# Generated by Django 2.1.3 on 2018-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0050_auto_20181114_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetNLScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, help_text='If the scan finished successfully.')),
                ('started', models.BooleanField(default=False, help_text='If the scan is started, normally this is a YES.')),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False, help_text='If the scan is complete.')),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True,
                                         help_text='The url where the status of the batch scan can be retrieved.', max_length=500, null=True)),
                ('message', models.CharField(blank=True,
                                             help_text='A status message received from the service', max_length=500, null=True)),
            ],
        ),
    ]
