#!/usr/bin/env bash

set -e -o pipefail

# build websecmap docker image
docker build . --tag websecmap/websecmap:latest

docker run -ti --name websecmap-$$ websecmap/websecmap:latest --help
docker cp websecmap-$$:/root/.cache/pip/ .pip-cache/
docker rm websecmap-$$
