#!/usr/bin/env bash

set -e -o pipefail

# build failmap docker image
docker build . --tag failmap/failmap:latest

docker run -ti --name failmap-$$ failmap/failmap:latest --help
docker cp failmap-$$:/root/.cache/pip .pip-cache/
