# Generated by Django 3.1.6 on 2021-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0001_squashed_0082_auto_20210417_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedscan",
            name="requested_at_when",
            field=models.DateTimeField(db_index=True),
        ),
    ]
