# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0007_auto_20170316_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsqualysscan',
            name='scan_moment',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
