# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0020_auto_20171013_1004"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointIp",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ip",
                    models.CharField(
                        help_text="IPv4 or IPv6 Address. Addresses have to be normalized to the compressed representation: removing as many zeros as possible. For example:  IPv6: abcd:0000:0000:00fd becomes abcd::fd, or IPv4: 127.000.000.001 = 127.0.0.1",
                        max_length=255,
                    ),
                ),
                (
                    "rdns_name",
                    models.CharField(
                        help_text="The reverse name can be a server name, containing a provider or anything else.It might contain the name of a yet undiscovered url or hint to a service.",
                        max_length=255,
                    ),
                ),
                ("discovered_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "is_unused",
                    models.IntegerField(
                        default=False,
                        help_text="If the address was used in the past, but not anymore.It's possible that the same address is more than once associated with and endpoint over time, as some providersrotate a set of IP addresses.",
                    ),
                ),
                ("is_unused_since", models.DateTimeField(blank=True, null=True)),
                ("is_unused_reason", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="endpoint",
            name="ip_version",
            field=models.IntegerField(
                default=4,
                help_text="Either IPv4 or IPv6. There are basically two possibilities to reach the endpoint, which due to immaturity often look very different. The old way is using IPv4addresses (4) and the newer method is uing IPv6 (6). The internet looks a whole lotdifferent between IPv4 or IPv6. That shouldn't be the case, but it is.",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="endpointip",
            name="endpoint",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="scanners.Endpoint"),
        ),
    ]
