# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0028_auto_20171113_1203"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="domain",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="ip",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="server_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
