# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0032_auto_20180208_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointgenericscan',
            name='explanation',
            field=models.CharField(
                default=0, help_text='Short explanation from the scanner on how the rating came to be.', max_length=9001),
        ),
    ]
