# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0034_auto_20180302_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpointgenericscan",
            name="domain",
            field=models.CharField(help_text="Deprecated. Text value representing the url scanned.", max_length=255),
        ),
        migrations.AlterField(
            model_name="urlgenericscan",
            name="domain",
            field=models.CharField(help_text="Deprecated. Text value representing the url scanned.", max_length=255),
        ),
    ]
