# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0035_auto_20180302_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointgenericscan',
            name='evidence',
            field=models.TextField(
                default=0, help_text='Content that might help understanding the result.', max_length=9001),
        ),
        migrations.AlterField(
            model_name='urlgenericscan',
            name='evidence',
            field=models.TextField(
                default=0, help_text='Content that might help understanding the result.', max_length=9001),
        ),
    ]
