# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0037_merge_20180313_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointgenericscan',
            name='domain',
            field=models.CharField(help_text='Deprecated. Text value representing the url scanned.', max_length=255),
        ),
    ]
