# Generated by Django 2.0.4 on 2018-05-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0038_auto_20180313_1045"),
    ]

    operations = [
        migrations.DeleteModel(
            name="State",
        ),
    ]
