# Generated by Django 2.0.4 on 2018-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0039_delete_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointgenericscan',
            name='rating',
            field=models.CharField(
                default=0, help_text="Preferably an integer, 'True' or 'False'. Keep ratings over time consistent.", max_length=10),
        ),
        migrations.AlterField(
            model_name='urlgenericscan',
            name='rating',
            field=models.CharField(
                default=0, help_text="Preferably an integer, 'True' or 'False'. Keep ratings over time consistent.", max_length=10),
        ),
    ]
