# Generated by Django 2.0.7 on 2018-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0043_auto_20180917_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_case_additional_notes",
            field=models.CharField(
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=512,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=255,
                verbose_name="case handled by",
            ),
        ),
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=255,
                verbose_name="explained by",
            ),
        ),
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_explained_on",
            field=models.DateTimeField(
                blank=True,
                help_text="From this moment the rating will be muted.",
                null=True,
                verbose_name="explained on",
            ),
        ),
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_explanation",
            field=models.CharField(
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=255,
                verbose_name="explanation",
            ),
        ),
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_explanation_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Set to one year in the future. Will expire automatically after a scan finds a change on this service. As long as the rating stays the same, the finding is explained and the issue ignored.",
                null=True,
                verbose_name="explanation valid until",
            ),
        ),
        migrations.AddField(
            model_name="endpointgenericscan",
            name="comply_or_explain_is_explained",
            field=models.BooleanField(
                default=False,
                help_text="Shorthand to indicate that something is explained. Only when this field is set to True, the explanation is ",
                verbose_name="is explained",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_case_additional_notes",
            field=models.CharField(
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=512,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=255,
                verbose_name="case handled by",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=255,
                verbose_name="explained by",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_explained_on",
            field=models.DateTimeField(
                blank=True,
                help_text="From this moment the rating will be muted.",
                null=True,
                verbose_name="explained on",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_explanation",
            field=models.CharField(
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=255,
                verbose_name="explanation",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_explanation_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Set to one year in the future. Will expire automatically after a scan finds a change on this service. As long as the rating stays the same, the finding is explained and the issue ignored.",
                null=True,
                verbose_name="explanation valid until",
            ),
        ),
        migrations.AddField(
            model_name="tlsqualysscan",
            name="comply_or_explain_is_explained",
            field=models.BooleanField(
                default=False,
                help_text="Shorthand to indicate that something is explained. Only when this field is set to True, the explanation is ",
                verbose_name="is explained",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_case_additional_notes",
            field=models.CharField(
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=512,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=255,
                verbose_name="case handled by",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=255,
                verbose_name="explained by",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_explained_on",
            field=models.DateTimeField(
                blank=True,
                help_text="From this moment the rating will be muted.",
                null=True,
                verbose_name="explained on",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_explanation",
            field=models.CharField(
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=255,
                verbose_name="explanation",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_explanation_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Set to one year in the future. Will expire automatically after a scan finds a change on this service. As long as the rating stays the same, the finding is explained and the issue ignored.",
                null=True,
                verbose_name="explanation valid until",
            ),
        ),
        migrations.AddField(
            model_name="tlsscan",
            name="comply_or_explain_is_explained",
            field=models.BooleanField(
                default=False,
                help_text="Shorthand to indicate that something is explained. Only when this field is set to True, the explanation is ",
                verbose_name="is explained",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_case_additional_notes",
            field=models.CharField(
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=512,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=255,
                verbose_name="case handled by",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=255,
                verbose_name="explained by",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_explained_on",
            field=models.DateTimeField(
                blank=True,
                help_text="From this moment the rating will be muted.",
                null=True,
                verbose_name="explained on",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_explanation",
            field=models.CharField(
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=255,
                verbose_name="explanation",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_explanation_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Set to one year in the future. Will expire automatically after a scan finds a change on this service. As long as the rating stays the same, the finding is explained and the issue ignored.",
                null=True,
                verbose_name="explanation valid until",
            ),
        ),
        migrations.AddField(
            model_name="urlgenericscan",
            name="comply_or_explain_is_explained",
            field=models.BooleanField(
                default=False,
                help_text="Shorthand to indicate that something is explained. Only when this field is set to True, the explanation is ",
                verbose_name="is explained",
            ),
        ),
    ]
