# Generated by Django 2.0.7 on 2018-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0045_auto_20180918_0859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tlsscan",
            name="evidence",
            field=models.TextField(
                blank=True, default=0, help_text="Content that might help understanding the result.", max_length=9001
            ),
        ),
    ]
