# Generated by Django 2.0.8 on 2018-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0047_auto_20180918_1217"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endpointgenericscan",
            options={"ordering": ["-rating_determined_on"]},
        ),
        migrations.AlterModelOptions(
            name="tlsqualysscan",
            options={"managed": True, "ordering": ["-rating_determined_on"]},
        ),
        migrations.AlterModelOptions(
            name="tlsscan",
            options={
                "ordering": ["-rating_determined_on"],
                "verbose_name": "tlsscan",
                "verbose_name_plural": "tlsscan",
            },
        ),
        migrations.AlterModelOptions(
            name="urlgenericscan",
            options={"ordering": ["-rating_determined_on"]},
        ),
        migrations.AlterField(
            model_name="endpointgenericscan",
            name="comply_or_explain_case_additional_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=9000,
                null=True,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AlterField(
            model_name="endpointgenericscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=512,
                null=True,
                verbose_name="case handled by",
            ),
        ),
        migrations.AlterField(
            model_name="endpointgenericscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=512,
                null=True,
                verbose_name="explained by",
            ),
        ),
        migrations.AlterField(
            model_name="endpointgenericscan",
            name="comply_or_explain_explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=2048,
                null=True,
                verbose_name="explanation",
            ),
        ),
        migrations.AlterField(
            model_name="tlsqualysscan",
            name="comply_or_explain_case_additional_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=9000,
                null=True,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AlterField(
            model_name="tlsqualysscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=512,
                null=True,
                verbose_name="case handled by",
            ),
        ),
        migrations.AlterField(
            model_name="tlsqualysscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=512,
                null=True,
                verbose_name="explained by",
            ),
        ),
        migrations.AlterField(
            model_name="tlsqualysscan",
            name="comply_or_explain_explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=2048,
                null=True,
                verbose_name="explanation",
            ),
        ),
        migrations.AlterField(
            model_name="tlsscan",
            name="comply_or_explain_case_additional_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=9000,
                null=True,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AlterField(
            model_name="tlsscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=512,
                null=True,
                verbose_name="case handled by",
            ),
        ),
        migrations.AlterField(
            model_name="tlsscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=512,
                null=True,
                verbose_name="explained by",
            ),
        ),
        migrations.AlterField(
            model_name="tlsscan",
            name="comply_or_explain_explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=2048,
                null=True,
                verbose_name="explanation",
            ),
        ),
        migrations.AlterField(
            model_name="urlgenericscan",
            name="comply_or_explain_case_additional_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes about the scenario for follow up. Things such as phone numbers, mail addresses, contact info.Will not be exported, but are not secret.",
                max_length=9000,
                null=True,
                verbose_name="additional case notes",
            ),
        ),
        migrations.AlterField(
            model_name="urlgenericscan",
            name="comply_or_explain_case_handled_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who entered the comply-or-explain information, so it's easy to find the right person to talk to in case of follow-ups.",
                max_length=512,
                null=True,
                verbose_name="case handled by",
            ),
        ),
        migrations.AlterField(
            model_name="urlgenericscan",
            name="comply_or_explain_explained_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please also refer to a thread, discussion or another fact that can be verified.",
                max_length=512,
                null=True,
                verbose_name="explained by",
            ),
        ),
        migrations.AlterField(
            model_name="urlgenericscan",
            name="comply_or_explain_explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text that helps explain why this result is not counted in the report. For example: a broken scanner or another edge-case that is mainly on the side of the scanning party. Having requested the supplier for a fix, or promising a fix should be stored as a promise, not as an explanation.",
                max_length=2048,
                null=True,
                verbose_name="explanation",
            ),
        ),
    ]
