# Generated by Django 2.1.3 on 2018-12-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0054_auto_20181213_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlsscan',
            name='endpoint',
        ),
        migrations.DeleteModel(
            name='TlsScan',
        ),
    ]
