# Generated by Django 2.2 on 2019-04-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0062_auto_20190411_1504"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endpointgenericscanscratchpad",
            old_name="when",
            new_name="at_when",
        ),
        migrations.RenameField(
            model_name="tlsqualysscratchpad",
            old_name="when",
            new_name="at_when",
        ),
    ]
