# Generated by Django 2.2.1 on 2019-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0065_auto_20190604_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetnlscan",
            name="last_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
