# Generated by Django 2.2.1 on 2019-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0066_internetnlscan_last_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(default=None, height_field='height_pixels', null=True,
                                    upload_to='screenshot', width_field='width_pixels'),
        ),
    ]
