# Generated by Django 2.2.1 on 2019-09-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0067_screenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(default=None, height_field='height_pixels', null=True,
                                    upload_to='screenshots/', width_field='width_pixels'),
        ),
    ]
