# Generated by Django 2.2.10 on 2020-05-06 13:13

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0071_auto_20200506_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetnlv2scan",
            name="metadata",
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="internetnlv2scan",
            name="retrieved_scan_report",
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
