# Generated by Django 2.2.10 on 2020-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0073_plannedscan_plannedscanerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedscan',
            name='finished_at_when',
            field=models.DateTimeField(help_text='when finished, timeout, error', null=True),
        ),
    ]
