# Generated by Django 3.1.6 on 2021-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0080_auto_20200907_0820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedscan",
            name="activity",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "unknown"), (1, "discover"), (2, "verify"), (3, "scan")],
                db_index=True,
                default=0,
                help_text="discover, verify or scan",
            ),
        ),
        migrations.AlterField(
            model_name="plannedscan",
            name="scanner",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "unknown"),
                    (1, "tls_qualys"),
                    (2, "dnssec"),
                    (3, "security_headers"),
                    (4, "plain_http"),
                    (5, "internet_nl_mail"),
                    (6, "ftp"),
                    (7, "dns_endpoints"),
                    (8, "internet_nl_web"),
                    (9, "subdomains"),
                    (10, "dns_known_subdomains"),
                    (11, "dns_clean_wildcards"),
                    (12, "http"),
                    (13, "verify_unresolvable"),
                    (14, "onboard"),
                    (15, "ipv6"),
                    (16, "dns_wildcard"),
                    (17, "dummy"),
                    (18, "screenshot"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="plannedscan",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "unknown"),
                    (1, "requested"),
                    (2, "picked_up"),
                    (3, "finished"),
                    (4, "error"),
                    (5, "timeout"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
