# Generated by Django 3.1.6 on 2021-04-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0081_auto_20210415_1758"),
    ]

    operations = []

    # Can't see from commit history what has changed here...
    # Doesn't really matter as the squashed migration gets it right.
