# Generated by Django 2.1.3 on 2018-12-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0047_auto_20181213_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Understandable name of the organization.', max_length=120, null=True)),
                ('enable_logins', models.BooleanField(blank=True, default=False, help_text='Inactive accounts cannot be logged-in to.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailmapOrganizationDataFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(help_text='Organization where urls come from.', on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, max_length=800, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the UrlList, for example name of the organization in it.', max_length=120, null=True)),
                ('account', models.ForeignKey(help_text='Who owns and manages this urllist.', on_delete=django.db.models.deletion.CASCADE, to='pro.Account')),
                ('urls', models.ManyToManyField(to='organizations.Url')),
            ],
        ),
        migrations.AddField(
            model_name='failmaporganizationdatafeed',
            name='urllist',
            field=models.ManyToManyField(to='pro.UrlList'),
        ),
    ]
