# Generated by Django 2.1.3 on 2018-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_auto_20181218_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescanrequest',
            name='scan_id',
            field=models.IntegerField(default=0, help_text='Makes it easy to find if a rescan is already requested.'),
        ),
    ]
