# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='N/A', help_text='name of the job', max_length=255),
            preserve_default=False,
        ),
    ]
