# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_auto_20180208_1318'),
        ('organizations', '0022_auto_20180119_1144'),
    ]

    operations = [
    ]
