# Generated by Django 2.0.3 on 2018-03-20 15:38

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_auto_20180320_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='area',
            field=djgeojson.fields.GeoJSONField(
                default=dict, help_text='GeoJson using the WGS84 (EPSG 4326) projection. Use simplified geometries to reduce the amount of data to transfer.', max_length=10000),
        ),
    ]
