# Generated by Django 2.1.3 on 2018-11-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0038_auto_20180824_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="These notes can contain information on WHY this organization was added. Can be handy if it's not straightforward. This helps with answering questions why the organization was added lateron. These notes will not be published, but are also not secret.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="These notes can contain information on WHY this URL was added. Can be handy if it's not straightforward. This helps with answering questions why the URL was added lateron. For example: some urls are owned via a 100% shareholder construction by a state company / municipality while the company itself is private. These notes will not be published, but are also not secret.", max_length=500, null=True),
        ),
    ]
